Pull Request for FCC: Budget App
bilalkhan13/Scientific-Computing-with-Python pull request #5
Opened 2022-08-06 11:41 UTC by bilalkhan13

2022-08-18 11:25 UTC, nf-khan reviewed
Done with partial review and review is in progress now

Use snake_case for variables

2022-08-18 11:25 UTC, nf-khan commented on budget-app/budget.py
> +        self.ledger.append(appendList)
We can directly append object in `self.ledger`

2022-08-18 11:25 UTC, nf-khan commented on budget-app/budget.py
> +            appendList = {"amount": -amount, "description": desc}
We can directly append object in `self.ledger`

2022-08-18 11:25 UTC, nf-khan commented on budget-app/budget.py
> +            return True
We can use ternary operator here

2022-08-18 11:25 UTC, nf-khan commented on budget-app/budget.py
> +        header = "".join(asteriks)
For `header` see python function so `header` can be printed only by one line and with that function we have no need of variables like `max_len`, `asteriks`

2022-08-18 11:25 UTC, nf-khan commented on budget-app/budget.py
> +        ledger_lines = ''.join([j for i in ledger_items for j in i])
We can assign `ledger_item` in string so we don't need `for` loop for `join`

2022-08-18 11:25 UTC, nf-khan commented on budget-app/budget.py
> +            whitespace = max_len
No need of `whitespace` and white spaces can be handled with `rjust` and `ljust`

2022-08-19 18:05 UTC, mehmoodak requested changes
Done with 1st review and left some comments. Apart from comments please address following things also.

1. Add proper title and description
2. `__pycache__` folder should not be uploaded .... already given this feedback in last PR
3. Add proper `README.md` file for the project

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +from xml.dom.minidom import CharacterData
Where are we using these 3 imports?

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    # Deposit Function
Function name is already clear so this comment doesn't add any value

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        self.ledger.append(appendList)
If we are appending directly then fine else `transaction` is a better name i.e. `appendList` is unclear name

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    # Withdraw Function
Same as above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        if self.check_funds(amount) == True:
No need of comparing it with true i.e. return value of function is already boolean

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        else:
This is an additional nesting .... we can avoid the else and `return false` directly

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    # Balance Function
Same as above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    # Check Funds Availability
Same as above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +            return True
No need of ternary .... condition is already giving us `boolean`

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    # Transfer Funds
Same as above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        else:
No need of `else` as suggested above.

BTW we can just `return False` at top based on the condition and then add the code for `True` case without any condition

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    # String Display
Extra comment

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        oneSideAsteriks = int(len(asteriks)/2)
Blank line above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        for item in self.ledger:
Blank line above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        category_len = len(self.category)
no need of variable because used only once

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +# Spend Chart
Extra comment

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    for category in categories:
blank line above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        for item in category.ledger:
1. blank line above
2. Can we use a better name than `item`?

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    for label in y_axis:
1. blank line above
2. improve name of `label` because this is not some string

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        for percentage in spent_percentage:
blank line above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +            else:
We can use ternary operator here instead of if/else

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    for name in category_names:
1. blank line above
2. Instead of doing it in a separate loop can we use the loop on line 82 for same purpose

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    for val in range(longest_name_length):
blank line above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        graph_content += " "
blank line above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        if val < longest_name_length-1:
blank line above

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +    spent_list = []
1. We can use only one line to assing `[]`
2. improve `spent_list` name
3. Instead of using separate array can we use single array of objects in which each object represent on catergory?

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        self.category = category
`self.name` is a better variable name because category is confusing as we also have same as classname

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +            self.ledger.append({"amount": -amount, "description": "Transfer to " + category.category})
`category.category` .... is this name fine?

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        total_amount = 0
`total_spent_amount` seems like a better name

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +                total_amount -= item['amount']
Can we use abs (absolute) function here?

See: [https://www.askpython.com/python/built-in-methods/python-abs-function](https://www.askpython.com/python/built-in-methods/python-abs-function)

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +        graph_content += str(label).rjust(3)+"|"
`label` is already a string so why we are converting it again here? BTW I think our array should have numbers instead of string i.e. keep the type as close as possible to the actual value inside it

2022-08-19 18:05 UTC, mehmoodak commented on budget-app/budget.py
> +                graph_content += "   "
We are using 3 whitespace here and above ..... and also we are using 1 space + 1 character + 1 space above .... so better to make this a function as we are using same logic in two places

2022-08-20 16:22 UTC, bilalkhan13 commented on budget-app/budget.py
> +from xml.dom.minidom import CharacterData
Removed.

2022-08-21 18:41 UTC, mehmoodak requested changes
Done with 2nd review

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +    def __init__(self, category):
`name` variable is better than `category`

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
No need of space here

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
no need of space here

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
no need of blank line

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
extra line

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +        return False if self.amount < amount else True
It should be `return not (self.amount < amount)` ..... no need of extra booleans

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
extra line

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
extra line

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +        max_len = 30
used only once so no need to create the variable

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +        for item in self.ledger:
`transaction` is a better name than `item` ..... do same in other places

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +        total = self.get_balance()
No need of `total` variable .... it is the current balance and we can directly call the function where needed

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
Extra line

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +    spent_list = []
Kindly implement this feedback

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
extra line

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
extra line

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
extra line

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +
extra line

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +def set_value(value=None):
If we assign `value = " "` here as default then we only need on statement here

2022-08-21 18:41 UTC, mehmoodak commented on budget-app/budget.py
> +            if len(name) > val:
User ternary

2022-08-25 15:31 UTC, mehmoodak approved these changes
Approving the feedback but left some comments so please incorporate those before merge.

2022-08-25 15:31 UTC, mehmoodak commented on budget-app/budget.py
> +        return  not self.amount < amount
There are two spaces between `return` and `not` ...... it should be one

2022-08-25 15:31 UTC, mehmoodak commented on budget-app/budget.py
> +def set_value(value=""):
This function can be written as

```
def set_value(value=" "):
    return " " + value + " "
```

2022-08-25 15:31 UTC, mehmoodak commented on budget-app/budget.py
> +            graph_content += " o " if percentage >= int(value) else "   "
We should use `set_value` function here .... in this way all of the graph output will be in one place i.e. if we need to change anything in future then it will be easier

2022-08-25 15:59 UTC, merged